/**
 * waves.js
 *
 * Wave definitions consumed by WaveSystem. Waves 1-5 are hand authored per
 * the design spec; wave 6+ is procedurally generated by scaling enemy
 * count, enemy type mix and an HP multiplier. Movement speed is
 * deliberately never scaled here - only count/mix/HP grow, and HP growth
 * is capped so late waves stay winnable rather than exploding forever.
 *
 * Each wave definition is a list of "spawn entries":
 *   { type: 'normal' | 'fast' | 'tank', count: number, hpMultiplier?: number }
 */

const HAND_AUTHORED_WAVES = [
  // Wave 1
  [{ type: 'normal', count: 10 }],
  // Wave 2
  [{ type: 'normal', count: 15 }],
  // Wave 3
  [
    { type: 'normal', count: 10 },
    { type: 'fast', count: 5 },
  ],
  // Wave 4
  [
    { type: 'normal', count: 10 },
    { type: 'fast', count: 10 },
  ],
  // Wave 5
  [
    { type: 'normal', count: 15 },
    { type: 'tank', count: 5 },
  ],
];

const MAX_HP_MULTIPLIER = 4.5;

function generateWave(waveNumber) {
  const extra = waveNumber - HAND_AUTHORED_WAVES.length;
  const hpMultiplier = Math.min(1 + extra * 0.12, MAX_HP_MULTIPLIER);

  const normalCount = 12 + extra * 2;
  const fastCount = Math.min(4 + extra * 2, 30);
  const tankCount = Math.min(2 + Math.floor(extra / 2), 20);

  const entries = [{ type: 'normal', count: normalCount, hpMultiplier }];

  if (extra >= 1) {
    entries.push({ type: 'fast', count: fastCount, hpMultiplier });
  }
  if (extra >= 2 && waveNumber % 2 === 0) {
    entries.push({ type: 'tank', count: tankCount, hpMultiplier });
  } else if (extra >= 4) {
    entries.push({ type: 'tank', count: Math.max(3, Math.floor(tankCount * 0.6)), hpMultiplier });
  }

  return entries;
}

/**
 * Returns the wave definition (array of spawn entries) for a given
 * 1-based wave number.
 */
export function getWaveDefinition(waveNumber) {
  if (waveNumber >= 1 && waveNumber <= HAND_AUTHORED_WAVES.length) {
    return HAND_AUTHORED_WAVES[waveNumber - 1];
  }
  return generateWave(waveNumber);
}

// Delay (ms) before the first wave and between a wave being cleared and
// the next one auto-starting.
export const NEXT_WAVE_COUNTDOWN_MS = 15000;
